version: 2
jobs:
  build:
    working_directory: ~/asgard
    docker:
      - image: circleci/node:8.11.2
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: false
    - run:
        name: Build Docker images
        command: make build
    - run:
        name: Show produced Docker images
        command: docker images
    - deploy:
        name: Publish application to docker hub
        command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID $DOCKER_HUB_PWD
            make push
