version: 2
jobs:
  build:
    working_directory: ~/asgard
    docker:
      - image: circleci/node:8.11.2
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Push to ECR
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install awscli
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t local:$TAG .
            eval `aws ecr get-login | sed -e's/-e none//'`
            docker tag local:$TAG $AWS_ECR_REGISTRY:$TAG
            docker push $AWS_ECR_REGISTRY:$TAG
